version: '3.4'

services:
  django:
    command: >
      bash -c "python3 manage.py migrate --noinput &&
               python3 manage.py collectstatic --noinput &&
               gunicorn ${PROJECT_NAME}.wsgi -b :8000 -w ${GUNICORN_WORKERS}"
