# Generated by Django 2.1 on 2018-09-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('views_count', models.IntegerField()),
                ('bookmarks_count', models.IntegerField()),
            ],
        ),
    ]
