# Generated by Django 2.1 on 2018-09-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='url',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
