# Generated by Django 2.1 on 2018-09-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0003_auto_20180922_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
