# Generated by Django 2.1 on 2018-09-22 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0004_auto_20180922_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='drawn_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 18, 57, 19, 517112, tzinfo=utc), verbose_name='Drawn at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
