# Generated by Django 2.1 on 2018-09-23 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0005_auto_20180922_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='caption',
        ),
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.TextField(default='123', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='bookmarks_count',
            field=models.IntegerField(verbose_name='Bookmarks count'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='tags',
            field=models.ManyToManyField(to='kirisame.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='views_count',
            field=models.IntegerField(verbose_name='Views count'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kirisame.Artist', verbose_name='Artist'),
            preserve_default=False,
        ),
    ]
