# Generated by Django 2.1 on 2018-09-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0009_auto_20180923_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='pages_count',
            field=models.IntegerField(default=1, verbose_name='Pages count'),
            preserve_default=False,
        ),
    ]
