# Generated by Django 2.1 on 2018-09-23 12:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0010_artwork_pages_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('image_urls', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Image URLS')),
                ('file_names', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='File names')),
                ('state', django_fsm.FSMIntegerField(choices=[(0, 'Planned'), (1, 'Downloaded'), (2, 'Scheduled'), (3, 'Published')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_published',
        ),
    ]
