# Generated by Django 2.1 on 2018-09-23 13:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0011_auto_20180923_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='toot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toot',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publish date'),
        ),
        migrations.AddField(
            model_name='toot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='toot',
            name='file_names',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='File names'),
        ),
    ]
