# Generated by Django 2.1 on 2018-09-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0013_auto_20180928_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
            },
        ),
        migrations.AlterModelOptions(
            name='artistmeta',
            options={'verbose_name': 'Artist Meta', 'verbose_name_plural': 'Artist Metas'},
        ),
        migrations.AlterModelOptions(
            name='artworkmeta',
            options={'verbose_name': 'Artwork Meta', 'verbose_name_plural': 'Artwork Metas'},
        ),
    ]
