# Generated by Django 2.1 on 2018-09-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0015_auto_20180929_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='toot',
            name='bot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='kirisame.Bot', verbose_name='Bot'),
            preserve_default=False,
        ),
    ]
