# Generated by Django 2.1 on 2018-09-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0017_toot_artworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toot',
            name='image_urls',
        ),
    ]
