# Generated by Django 2.1 on 2018-09-30 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0018_remove_toot_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='drawn_at',
        ),
        migrations.AddField(
            model_name='artwork',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 14, 41, 10, 144821, tzinfo=utc), verbose_name='Published at'),
            preserve_default=False,
        ),
    ]
