# Generated by Django 2.1 on 2018-09-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0019_auto_20180930_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='pages_count',
        ),
        migrations.AddField(
            model_name='artwork',
            name='images_count',
            field=models.IntegerField(default=1, verbose_name='Images count'),
            preserve_default=False,
        ),
    ]
