# Generated by Django 2.1 on 2018-09-30 15:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0021_auto_20180930_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='toot',
            name='media_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Media IDs'),
        ),
    ]
