# Generated by Django 2.1 on 2018-10-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0022_toot_media_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'Illust'), (1, 'Manga'), (2, 'Ugoira')], default=0, verbose_name='Source'),
            preserve_default=False,
        ),
    ]
