# Generated by Django 2.1 on 2018-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0023_artwork_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='access_token',
            field=models.CharField(default='42', max_length=255, verbose_name='Access token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='base_url',
            field=models.CharField(default='42', max_length=255, verbose_name='Base URL'),
            preserve_default=False,
        ),
    ]
