# Generated by Django 2.1 on 2018-10-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirisame', '0024_auto_20181006_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='toot',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID assigned after scheduling', max_length=255, null=True, verbose_name='Task ID'),
        ),
        migrations.AddField(
            model_name='toot',
            name='toot_id',
            field=models.CharField(blank=True, help_text='Mastodon toot ID assigned after publishing', max_length=255, null=True, verbose_name='Toot ID'),
        ),
    ]
